spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: update

  profiles:
    include: aws


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
